name: Tests

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: 
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
    - uses: actions/checkout@v4
    - name: Cache uv
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install dagger
      run: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
    - name: Initialize dagger
      run: dagger init --sdk=python --source=./dagger
      working-directory: dagger
    - name: Install dependencies
      run: uv sync --all-extras --dev --cache-dir ~/.cache/uv --locked
      working-directory: dagger
    - name: Analysing the code with ruff
      run: |
        uv run ruff check .
      working-directory: dagger
    - name: Test code without integration tests
      run: |
        uv run pytest -m "not integration" -s .
      working-directory: dagger
    